# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mcp_cpp <- function(t, lambda, gamma) {
    .Call('_penMlogistic_mcp_cpp', PACKAGE = 'penMlogistic', t, lambda, gamma)
}

scad_cpp <- function(t, lambda, gamma) {
    .Call('_penMlogistic_scad_cpp', PACKAGE = 'penMlogistic', t, lambda, gamma)
}

norm_quotient_cpp <- function(beta, lambda) {
    .Call('_penMlogistic_norm_quotient_cpp', PACKAGE = 'penMlogistic', beta, lambda)
}

elastic_net_cpp <- function(t, lambda, gamma) {
    .Call('_penMlogistic_elastic_net_cpp', PACKAGE = 'penMlogistic', t, lambda, gamma)
}

norm_quotient_mod_cpp <- function(beta, lambda, constant) {
    .Call('_penMlogistic_norm_quotient_mod_cpp', PACKAGE = 'penMlogistic', beta, lambda, constant)
}

pnorm_cpp <- function(x) {
    .Call('_penMlogistic_pnorm_cpp', PACKAGE = 'penMlogistic', x)
}

aux_fun_1 <- function(s) {
    .Call('_penMlogistic_aux_fun_1', PACKAGE = 'penMlogistic', s)
}

rho_ch_cpp <- function(t, k = 0.5) {
    .Call('_penMlogistic_rho_ch_cpp', PACKAGE = 'penMlogistic', t, k)
}

dev_cpp <- function(score, y) {
    .Call('_penMlogistic_dev_cpp', PACKAGE = 'penMlogistic', score, y)
}

der_rho_ch_cpp <- function(t, k = 0.5) {
    .Call('_penMlogistic_der_rho_ch_cpp', PACKAGE = 'penMlogistic', t, k)
}

G_ch_cpp <- function(t, k = 0.5) {
    .Call('_penMlogistic_G_ch_cpp', PACKAGE = 'penMlogistic', t, k)
}

inv_logit_cpp <- function(u) {
    .Call('_penMlogistic_inv_logit_cpp', PACKAGE = 'penMlogistic', u)
}

phi_ch_cpp <- function(score, y) {
    .Call('_penMlogistic_phi_ch_cpp', PACKAGE = 'penMlogistic', score, y)
}

der_phi_0_ch_cpp <- function(score) {
    .Call('_penMlogistic_der_phi_0_ch_cpp', PACKAGE = 'penMlogistic', score)
}

der_phi_ch_cpp <- function(score, y) {
    .Call('_penMlogistic_der_phi_ch_cpp', PACKAGE = 'penMlogistic', score, y)
}

get_scores <- function(X, beta, beta0) {
    .Call('_penMlogistic_get_scores', PACKAGE = 'penMlogistic', X, beta, beta0)
}

eval_loss_function_ch_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_loss_function_ch_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

eval_der_loss_function_ch_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_der_loss_function_ch_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

der_dev_cpp <- function(score, y) {
    .Call('_penMlogistic_der_dev_cpp', PACKAGE = 'penMlogistic', score, y)
}

eval_loss_function_dev_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_loss_function_dev_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

eval_der_loss_function_dev_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_der_loss_function_dev_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

der_rho_div_cpp <- function(t, c = 0.5) {
    .Call('_penMlogistic_der_rho_div_cpp', PACKAGE = 'penMlogistic', t, c)
}

G_div_cpp <- function(t, c = 0.5) {
    .Call('_penMlogistic_G_div_cpp', PACKAGE = 'penMlogistic', t, c)
}

rho_div_cpp <- function(t, c = 0.5) {
    .Call('_penMlogistic_rho_div_cpp', PACKAGE = 'penMlogistic', t, c)
}

phi_div_cpp <- function(score, y) {
    .Call('_penMlogistic_phi_div_cpp', PACKAGE = 'penMlogistic', score, y)
}

der_phi_0_div_cpp <- function(score, c = 0.5) {
    .Call('_penMlogistic_der_phi_0_div_cpp', PACKAGE = 'penMlogistic', score, c)
}

der_phi_div_cpp <- function(score, y) {
    .Call('_penMlogistic_der_phi_div_cpp', PACKAGE = 'penMlogistic', score, y)
}

eval_loss_function_div_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_loss_function_div_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

eval_der_loss_function_div_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_der_loss_function_div_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

phi_lse_cpp <- function(score, y) {
    .Call('_penMlogistic_phi_lse_cpp', PACKAGE = 'penMlogistic', score, y)
}

der_phi_lse_cpp <- function(score, y) {
    .Call('_penMlogistic_der_phi_lse_cpp', PACKAGE = 'penMlogistic', score, y)
}

eval_loss_function_lse_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_loss_function_lse_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

eval_der_loss_function_lse_cpp <- function(X, Y, beta, beta0, weights) {
    .Call('_penMlogistic_eval_der_loss_function_lse_cpp', PACKAGE = 'penMlogistic', X, Y, beta, beta0, weights)
}

